github_profile: alyson-mei

repos:
  - repo_name: media-db-v2
    local_path: /home/alyson/Vaults/Media
    visibility: public

  - repo_name: mathematics
    local_path: /home/alyson/Vaults/Math Notes
    visibility: public

schedule:
  interval_minutes: 5  # recommended: 5 minutes or more